DROP TABLE IF EXISTS producers;

CREATE TABLE producers(
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) UNIQUE,
Firmenname VARCHAR(50) NOT NULL UNIQUE,
Steuernummer VARCHAR(50) NOT NULL UNIQUE
);
